package quickjs:timeout;

world timeout {
  export run: func();
  export parallel: func();
  export use-next-tick: func();
  export await-runtime-idle: func();
  export await-runtime-idle-error: func() -> string;
  export await-runtime-idle-exit: func() -> s32;
  export await-runtime-idle-exit-with-pending-fetch: func(port: u16) -> s32;
  export await-runtime-idle-handled-error: func();
}
