declare module 'crypto' {
  export function newUuids(): Promise<[string, string]>;
  export function randomS8(count: number): Promise<number[]>;
  export function randomU32(count: number): Promise<number[]>;
  export function sha256Hex(input: string): Promise<string>;
  export function sha256MultiUpdate(parts: string[]): Promise<string>;
  export function hashWithAlgorithm(algorithm: string, input: string): Promise<string>;
  export function hashOneShot(algorithm: string, input: string): Promise<string>;
  export function listHashes(): Promise<string[]>;
  export function generateRandomBytes(size: number): Promise<Uint8Array>;
  export function generateRandomInt(min: bigint, max: bigint): Promise<bigint>;
  export function checkTimingSafeEqual(a: string, b: string): Promise<boolean>;
  export function hmacHex(algorithm: string, key: string, data: string): Promise<string>;
  export function hmacMultiUpdate(algorithm: string, key: string, parts: string[]): Promise<string>;
  export function pbkdf2Sha256Hex(password: string, salt: string, iterations: number, keylen: number): Promise<string>;
  export function scryptHex(password: string, salt: string, keylen: number): Promise<string>;
  export function hkdfSha256Hex(ikm: string, salt: string, info: string, keylen: number): Promise<string>;
  export function listCiphers(): Promise<string[]>;
  export function aesCbcRoundtrip(plaintext: string, keyHex: string, ivHex: string): Promise<string>;
  export function aesCtrRoundtrip(plaintext: string, keyHex: string, ivHex: string): Promise<string>;
  export function aesGcmRoundtrip(plaintext: string, keyHex: string, ivHex: string, aadText: string): Promise<string>;
  export function chacha20Poly1305Roundtrip(plaintext: string, keyHex: string, ivHex: string, aadText: string): Promise<string>;
  export function aesGcmEncryptHex(plaintext: string, keyHex: string, ivHex: string): Promise<string>;
  export function ed25519SignVerify(message: string): Promise<boolean>;
  export function ecdsaP256SignVerify(message: string): Promise<boolean>;
  export function ecdsaSecp256k1SignVerify(message: string): Promise<boolean>;
  export function ed25519KeyType(): Promise<string>;
  export function ecdsaP256ExportImportVerify(message: string): Promise<boolean>;
  export function ed25519WrongKeyVerify(message: string): Promise<boolean>;
  export function listCurves(): Promise<string[]>;
  export function getConstants(): Promise<string>;
  export function subtleDigestSha256(input: string): Promise<string>;
  export function subtleSignVerifyHmac(message: string): Promise<boolean>;
  export function subtleSignVerifyEd25519(message: string): Promise<boolean>;
}
