declare module 'node-http' {
  export function httpGet(port: number): Promise<void>;
  export function httpPostJson(port: number): Promise<void>;
  export function httpRequestWithHeaders(port: number): Promise<void>;
  export function httpConstants(): Promise<void>;
  export function httpSelfConnect(): Promise<void>;
  export function httpSelfConnectPost(): Promise<void>;
  export function httpAbortIsolation(): Promise<boolean>;
  export function httpResponseLifecycle(): Promise<boolean>;
  export function httpPipelinedResponseOrder(): Promise<boolean>;
  export function httpHalfOpenPipelinedRequests(): Promise<boolean>;
  export function httpPipelinedCloseLifecycle(): Promise<boolean>;
  export function httpPipelinedConnectionClose(): Promise<boolean>;
  export function httpPipelinedActiveTimeout(): Promise<boolean>;
  export function httpCloseIdleConnections(): Promise<boolean>;
  export function httpIdleResourceReclamation(): Promise<boolean>;
  export function httpZeroKeepAliveTimeout(): Promise<boolean>;
  export function httpUnreadRequestBodyDisposal(): Promise<boolean>;
  export function httpServerRequestDestroy(): Promise<boolean>;
  export function httpPartiallyConsumedRequestBody(): Promise<boolean>;
  export function httpResumeScheduledRequestBody(): Promise<boolean>;
  export function httpCompleteUnreadRequestBody(): Promise<boolean>;
  export function httpClientResponseOwnership(): Promise<boolean>;
  export function httpInformationalWriteAfterClose(): Promise<boolean>;
  export function httpMaxRequestsClosesSocket(): Promise<boolean>;
  export function netWritevBoundaries(): Promise<boolean>;
  export function httpPipelinedMaxRequests(): Promise<boolean>;
  export function httpCustomConnectionRejected(): Promise<boolean>;
  export function httpResponsePersistence(): Promise<boolean>;
  export function httpFalsyPortUsesProtocolDefault(): Promise<boolean>;
}
