// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[allow(dead_code, clippy::all)]
pub mod golem {
  pub mod websocket {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod client {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type Pollable = super::super::super::wasi::io::poll::Pollable;
      #[derive(Clone)]
      pub struct CloseInfo {
        pub code: u16,
        pub reason: _rt::String,
      }
      impl ::core::fmt::Debug for CloseInfo {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("CloseInfo").field("code", &self.code).field("reason", &self.reason).finish()
        }
      }
      #[derive(Clone)]
      pub enum Error {
        ConnectionFailure(_rt::String),
        SendFailure(_rt::String),
        ReceiveFailure(_rt::String),
        ProtocolError(_rt::String),
        Closed(Option<CloseInfo>),
        Other(_rt::String),
      }
      impl ::core::fmt::Debug for Error {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            Error::ConnectionFailure(e) => {
              f.debug_tuple("Error::ConnectionFailure").field(e).finish()
            }
            Error::SendFailure(e) => {
              f.debug_tuple("Error::SendFailure").field(e).finish()
            }
            Error::ReceiveFailure(e) => {
              f.debug_tuple("Error::ReceiveFailure").field(e).finish()
            }
            Error::ProtocolError(e) => {
              f.debug_tuple("Error::ProtocolError").field(e).finish()
            }
            Error::Closed(e) => {
              f.debug_tuple("Error::Closed").field(e).finish()
            }
            Error::Other(e) => {
              f.debug_tuple("Error::Other").field(e).finish()
            }
          }
        }
      }
      impl ::core::fmt::Display for Error {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          write!(f, "{:?}", self)
        }
      }

      impl std::error::Error for Error {}
      /// A WebSocket message — text or binary
      #[derive(Clone)]
      pub enum Message {
        Text(_rt::String),
        Binary(_rt::Vec::<u8>),
      }
      impl ::core::fmt::Debug for Message {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            Message::Text(e) => {
              f.debug_tuple("Message::Text").field(e).finish()
            }
            Message::Binary(e) => {
              f.debug_tuple("Message::Binary").field(e).finish()
            }
          }
        }
      }
      /// A WebSocket connection resource

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct WebsocketConnection{
        handle: _rt::Resource<WebsocketConnection>,
      }

      impl WebsocketConnection{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for WebsocketConnection{
        #[inline]
        unsafe fn drop(_handle: u32) {
          #[cfg(not(target_arch = "wasm32"))]
          unreachable!();

          #[cfg(target_arch = "wasm32")]
          {
            #[link(wasm_import_module = "golem:websocket/client@1.5.0")]
            unsafe extern "C" {
              #[link_name = "[resource-drop]websocket-connection"]
              fn drop(_: u32);
            }

            unsafe { drop(_handle) };
          }
        }
      }
      
      impl WebsocketConnection {
        #[allow(unused_unsafe, clippy::all)]
        /// Connect to a WebSocket server at the given URL (ws:// or wss://)
        /// Optional headers for auth, subprotocols, etc.
        pub fn connect(url: &str,headers: Option<&[(_rt::String,_rt::String,)]>,) -> Result<WebsocketConnection,Error>{
          unsafe {
            let mut cleanup_list = _rt::Vec::new();

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 6*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 6*::core::mem::size_of::<*const u8>()]);
            let vec0 = url;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let (result5_0,result5_1,result5_2,) = match headers {
              Some(e) => {
                let vec4 = e;
                let len4 = vec4.len();
                let layout4 = _rt::alloc::Layout::from_size_align_unchecked(vec4.len() * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
                let result4 = if layout4.size() != 0 {
                  let ptr = _rt::alloc::alloc(layout4).cast::<u8>();
                  if ptr.is_null()
                  {
                    _rt::alloc::handle_alloc_error(layout4);
                  }
                  ptr
                }else {
                  ::core::ptr::null_mut()
                };
                for (i, e) in vec4.into_iter().enumerate() {
                  let base = result4.add(i * (4*::core::mem::size_of::<*const u8>()));
                  {
                    let (t1_0, t1_1, ) = e;
                    let vec2 = t1_0;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    let vec3 = t1_1;
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr3.cast_mut();
                  }
                }
                cleanup_list.extend_from_slice(&[(result4, layout4),]);

                (1i32, result4, len4)
              },
              None => {
                (0i32, ::core::ptr::null_mut(), 0usize)
              },
            };let ptr6 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "golem:websocket/client@1.5.0")]
            unsafe extern "C" {
              #[link_name = "[static]websocket-connection.connect"]
              fn wit_import7(_: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import7(_: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, ){ unreachable!() }
            unsafe { wit_import7(ptr0.cast_mut(), len0, result5_0, result5_1, result5_2, ptr6) };
            let l8 = i32::from(*ptr6.add(0).cast::<u8>());
            let result32 = match l8 {
              0 => {
                let e = {
                  let l9 = *ptr6.add(::core::mem::size_of::<*const u8>()).cast::<i32>();

                  unsafe { WebsocketConnection::from_handle(l9 as u32) }
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l10 = i32::from(*ptr6.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v31 = match l10 {
                    0 => {
                      let e31 = {
                        let l11 = *ptr6.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l12 = *ptr6.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len13 = l12;
                        let bytes13 = _rt::Vec::from_raw_parts(l11.cast(), len13, len13);

                        _rt::string_lift(bytes13)
                      };
                      Error::ConnectionFailure(e31)
                    }
                    1 => {
                      let e31 = {
                        let l14 = *ptr6.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l15 = *ptr6.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len16 = l15;
                        let bytes16 = _rt::Vec::from_raw_parts(l14.cast(), len16, len16);

                        _rt::string_lift(bytes16)
                      };
                      Error::SendFailure(e31)
                    }
                    2 => {
                      let e31 = {
                        let l17 = *ptr6.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l18 = *ptr6.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len19 = l18;
                        let bytes19 = _rt::Vec::from_raw_parts(l17.cast(), len19, len19);

                        _rt::string_lift(bytes19)
                      };
                      Error::ReceiveFailure(e31)
                    }
                    3 => {
                      let e31 = {
                        let l20 = *ptr6.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l21 = *ptr6.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len22 = l21;
                        let bytes22 = _rt::Vec::from_raw_parts(l20.cast(), len22, len22);

                        _rt::string_lift(bytes22)
                      };
                      Error::ProtocolError(e31)
                    }
                    4 => {
                      let e31 = {
                        let l23 = i32::from(*ptr6.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>());

                        match l23 {
                          0 => None,
                          1 => {
                            let e = {
                              let l24 = i32::from(*ptr6.add(3*::core::mem::size_of::<*const u8>()).cast::<u16>());
                              let l25 = *ptr6.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                              let l26 = *ptr6.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
                              let len27 = l26;
                              let bytes27 = _rt::Vec::from_raw_parts(l25.cast(), len27, len27);

                              CloseInfo{
                                code: l24 as u16,
                                reason: _rt::string_lift(bytes27),
                              }
                            };
                            Some(e)
                          }
                          _ => _rt::invalid_enum_discriminant(),
                        }
                      };
                      Error::Closed(e31)
                    }
                    n => {
                      debug_assert_eq!(n, 5, "invalid enum discriminant");
                      let e31 = {
                        let l28 = *ptr6.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l29 = *ptr6.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len30 = l29;
                        let bytes30 = _rt::Vec::from_raw_parts(l28.cast(), len30, len30);

                        _rt::string_lift(bytes30)
                      };
                      Error::Other(e31)
                    }
                  };

                  v31
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            for (ptr, layout) in cleanup_list {

              if layout.size() != 0 {

                _rt::alloc::dealloc(ptr.cast(), layout);

              }

            }
            result32
          }
        }
      }
      impl WebsocketConnection {
        #[allow(unused_unsafe, clippy::all)]
        /// Send a message (text or binary)
        pub fn send(&self,message: &Message,) -> Result<(),Error>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 6*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 6*::core::mem::size_of::<*const u8>()]);
            let (result2_0,result2_1,result2_2,) = match message {
              Message::Text(e) => {
                let vec0 = e;
                let ptr0 = vec0.as_ptr().cast::<u8>();
                let len0 = vec0.len();

                (0i32, ptr0.cast_mut(), len0)
              },
              Message::Binary(e) => {
                let vec1 = e;
                let ptr1 = vec1.as_ptr().cast::<u8>();
                let len1 = vec1.len();

                (1i32, ptr1.cast_mut(), len1)
              },
            };
            let ptr3 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "golem:websocket/client@1.5.0")]
            unsafe extern "C" {
              #[link_name = "[method]websocket-connection.send"]
              fn wit_import4(_: i32, _: i32, _: *mut u8, _: usize, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import4(_: i32, _: i32, _: *mut u8, _: usize, _: *mut u8, ){ unreachable!() }
            unsafe { wit_import4((self).handle() as i32, result2_0, result2_1, result2_2, ptr3) };
            let l5 = i32::from(*ptr3.add(0).cast::<u8>());
            let result28 = match l5 {
              0 => {
                let e = ();
                Ok(e)
              }
              1 => {
                let e = {
                  let l6 = i32::from(*ptr3.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v27 = match l6 {
                    0 => {
                      let e27 = {
                        let l7 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l8 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len9 = l8;
                        let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);

                        _rt::string_lift(bytes9)
                      };
                      Error::ConnectionFailure(e27)
                    }
                    1 => {
                      let e27 = {
                        let l10 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l11 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len12 = l11;
                        let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);

                        _rt::string_lift(bytes12)
                      };
                      Error::SendFailure(e27)
                    }
                    2 => {
                      let e27 = {
                        let l13 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l14 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len15 = l14;
                        let bytes15 = _rt::Vec::from_raw_parts(l13.cast(), len15, len15);

                        _rt::string_lift(bytes15)
                      };
                      Error::ReceiveFailure(e27)
                    }
                    3 => {
                      let e27 = {
                        let l16 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l17 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len18 = l17;
                        let bytes18 = _rt::Vec::from_raw_parts(l16.cast(), len18, len18);

                        _rt::string_lift(bytes18)
                      };
                      Error::ProtocolError(e27)
                    }
                    4 => {
                      let e27 = {
                        let l19 = i32::from(*ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>());

                        match l19 {
                          0 => None,
                          1 => {
                            let e = {
                              let l20 = i32::from(*ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<u16>());
                              let l21 = *ptr3.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                              let l22 = *ptr3.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
                              let len23 = l22;
                              let bytes23 = _rt::Vec::from_raw_parts(l21.cast(), len23, len23);

                              CloseInfo{
                                code: l20 as u16,
                                reason: _rt::string_lift(bytes23),
                              }
                            };
                            Some(e)
                          }
                          _ => _rt::invalid_enum_discriminant(),
                        }
                      };
                      Error::Closed(e27)
                    }
                    n => {
                      debug_assert_eq!(n, 5, "invalid enum discriminant");
                      let e27 = {
                        let l24 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l25 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len26 = l25;
                        let bytes26 = _rt::Vec::from_raw_parts(l24.cast(), len26, len26);

                        _rt::string_lift(bytes26)
                      };
                      Error::Other(e27)
                    }
                  };

                  v27
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result28
          }
        }
      }
      impl WebsocketConnection {
        #[allow(unused_unsafe, clippy::all)]
        /// Receive the next message (blocks until available)
        pub fn receive(&self,) -> Result<Message,Error>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 6*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 6*::core::mem::size_of::<*const u8>()]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "golem:websocket/client@1.5.0")]
            unsafe extern "C" {
              #[link_name = "[method]websocket-connection.receive"]
              fn wit_import1(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ){ unreachable!() }
            unsafe { wit_import1((self).handle() as i32, ptr0) };
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result33 = match l2 {
              0 => {
                let e = {
                  let l3 = i32::from(*ptr0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v10 = match l3 {
                    0 => {
                      let e10 = {
                        let l4 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l5 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len6 = l5;
                        let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);

                        _rt::string_lift(bytes6)
                      };
                      Message::Text(e10)
                    }
                    n => {
                      debug_assert_eq!(n, 1, "invalid enum discriminant");
                      let e10 = {
                        let l7 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l8 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len9 = l8;

                        _rt::Vec::from_raw_parts(l7.cast(), len9, len9)
                      };
                      Message::Binary(e10)
                    }
                  };

                  v10
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l11 = i32::from(*ptr0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v32 = match l11 {
                    0 => {
                      let e32 = {
                        let l12 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l13 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len14 = l13;
                        let bytes14 = _rt::Vec::from_raw_parts(l12.cast(), len14, len14);

                        _rt::string_lift(bytes14)
                      };
                      Error::ConnectionFailure(e32)
                    }
                    1 => {
                      let e32 = {
                        let l15 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l16 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len17 = l16;
                        let bytes17 = _rt::Vec::from_raw_parts(l15.cast(), len17, len17);

                        _rt::string_lift(bytes17)
                      };
                      Error::SendFailure(e32)
                    }
                    2 => {
                      let e32 = {
                        let l18 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l19 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len20 = l19;
                        let bytes20 = _rt::Vec::from_raw_parts(l18.cast(), len20, len20);

                        _rt::string_lift(bytes20)
                      };
                      Error::ReceiveFailure(e32)
                    }
                    3 => {
                      let e32 = {
                        let l21 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l22 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len23 = l22;
                        let bytes23 = _rt::Vec::from_raw_parts(l21.cast(), len23, len23);

                        _rt::string_lift(bytes23)
                      };
                      Error::ProtocolError(e32)
                    }
                    4 => {
                      let e32 = {
                        let l24 = i32::from(*ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>());

                        match l24 {
                          0 => None,
                          1 => {
                            let e = {
                              let l25 = i32::from(*ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<u16>());
                              let l26 = *ptr0.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                              let l27 = *ptr0.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
                              let len28 = l27;
                              let bytes28 = _rt::Vec::from_raw_parts(l26.cast(), len28, len28);

                              CloseInfo{
                                code: l25 as u16,
                                reason: _rt::string_lift(bytes28),
                              }
                            };
                            Some(e)
                          }
                          _ => _rt::invalid_enum_discriminant(),
                        }
                      };
                      Error::Closed(e32)
                    }
                    n => {
                      debug_assert_eq!(n, 5, "invalid enum discriminant");
                      let e32 = {
                        let l29 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l30 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len31 = l30;
                        let bytes31 = _rt::Vec::from_raw_parts(l29.cast(), len31, len31);

                        _rt::string_lift(bytes31)
                      };
                      Error::Other(e32)
                    }
                  };

                  v32
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result33
          }
        }
      }
      impl WebsocketConnection {
        #[allow(unused_unsafe, clippy::all)]
        /// Receive the next message with a timeout in milliseconds.
        /// Returns none if the timeout expires before a message arrives.
        pub fn receive_with_timeout(&self,timeout_ms: u64,) -> Result<Option<Message>,Error>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 6*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 6*::core::mem::size_of::<*const u8>()]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "golem:websocket/client@1.5.0")]
            unsafe extern "C" {
              #[link_name = "[method]websocket-connection.receive-with-timeout"]
              fn wit_import1(_: i32, _: i64, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: i64, _: *mut u8, ){ unreachable!() }
            unsafe { wit_import1((self).handle() as i32, _rt::as_i64(&timeout_ms), ptr0) };
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result34 = match l2 {
              0 => {
                let e = {
                  let l3 = i32::from(*ptr0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());

                  match l3 {
                    0 => None,
                    1 => {
                      let e = {
                        let l4 = i32::from(*ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>());
                        let v11 = match l4 {
                          0 => {
                            let e11 = {
                              let l5 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                              let l6 = *ptr0.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
                              let len7 = l6;
                              let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);

                              _rt::string_lift(bytes7)
                            };
                            Message::Text(e11)
                          }
                          n => {
                            debug_assert_eq!(n, 1, "invalid enum discriminant");
                            let e11 = {
                              let l8 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                              let l9 = *ptr0.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
                              let len10 = l9;

                              _rt::Vec::from_raw_parts(l8.cast(), len10, len10)
                            };
                            Message::Binary(e11)
                          }
                        };

                        v11
                      };
                      Some(e)
                    }
                    _ => _rt::invalid_enum_discriminant(),
                  }
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l12 = i32::from(*ptr0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v33 = match l12 {
                    0 => {
                      let e33 = {
                        let l13 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l14 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len15 = l14;
                        let bytes15 = _rt::Vec::from_raw_parts(l13.cast(), len15, len15);

                        _rt::string_lift(bytes15)
                      };
                      Error::ConnectionFailure(e33)
                    }
                    1 => {
                      let e33 = {
                        let l16 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l17 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len18 = l17;
                        let bytes18 = _rt::Vec::from_raw_parts(l16.cast(), len18, len18);

                        _rt::string_lift(bytes18)
                      };
                      Error::SendFailure(e33)
                    }
                    2 => {
                      let e33 = {
                        let l19 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l20 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len21 = l20;
                        let bytes21 = _rt::Vec::from_raw_parts(l19.cast(), len21, len21);

                        _rt::string_lift(bytes21)
                      };
                      Error::ReceiveFailure(e33)
                    }
                    3 => {
                      let e33 = {
                        let l22 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l23 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len24 = l23;
                        let bytes24 = _rt::Vec::from_raw_parts(l22.cast(), len24, len24);

                        _rt::string_lift(bytes24)
                      };
                      Error::ProtocolError(e33)
                    }
                    4 => {
                      let e33 = {
                        let l25 = i32::from(*ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>());

                        match l25 {
                          0 => None,
                          1 => {
                            let e = {
                              let l26 = i32::from(*ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<u16>());
                              let l27 = *ptr0.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                              let l28 = *ptr0.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
                              let len29 = l28;
                              let bytes29 = _rt::Vec::from_raw_parts(l27.cast(), len29, len29);

                              CloseInfo{
                                code: l26 as u16,
                                reason: _rt::string_lift(bytes29),
                              }
                            };
                            Some(e)
                          }
                          _ => _rt::invalid_enum_discriminant(),
                        }
                      };
                      Error::Closed(e33)
                    }
                    n => {
                      debug_assert_eq!(n, 5, "invalid enum discriminant");
                      let e33 = {
                        let l30 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l31 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len32 = l31;
                        let bytes32 = _rt::Vec::from_raw_parts(l30.cast(), len32, len32);

                        _rt::string_lift(bytes32)
                      };
                      Error::Other(e33)
                    }
                  };

                  v33
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result34
          }
        }
      }
      impl WebsocketConnection {
        #[allow(unused_unsafe, clippy::all)]
        /// Send a close frame with optional code and reason
        pub fn close(&self,code: Option<u16>,reason: Option<&str>,) -> Result<(),Error>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 6*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 6*::core::mem::size_of::<*const u8>()]);
            let (result0_0,result0_1,) = match code {
              Some(e) => (1i32, _rt::as_i32(e)),
              None => {
                (0i32, 0i32)
              },
            };let (result2_0,result2_1,result2_2,) = match reason {
              Some(e) => {
                let vec1 = e;
                let ptr1 = vec1.as_ptr().cast::<u8>();
                let len1 = vec1.len();

                (1i32, ptr1.cast_mut(), len1)
              },
              None => {
                (0i32, ::core::ptr::null_mut(), 0usize)
              },
            };let ptr3 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "golem:websocket/client@1.5.0")]
            unsafe extern "C" {
              #[link_name = "[method]websocket-connection.close"]
              fn wit_import4(_: i32, _: i32, _: i32, _: i32, _: *mut u8, _: usize, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import4(_: i32, _: i32, _: i32, _: i32, _: *mut u8, _: usize, _: *mut u8, ){ unreachable!() }
            unsafe { wit_import4((self).handle() as i32, result0_0, result0_1, result2_0, result2_1, result2_2, ptr3) };
            let l5 = i32::from(*ptr3.add(0).cast::<u8>());
            let result28 = match l5 {
              0 => {
                let e = ();
                Ok(e)
              }
              1 => {
                let e = {
                  let l6 = i32::from(*ptr3.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v27 = match l6 {
                    0 => {
                      let e27 = {
                        let l7 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l8 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len9 = l8;
                        let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);

                        _rt::string_lift(bytes9)
                      };
                      Error::ConnectionFailure(e27)
                    }
                    1 => {
                      let e27 = {
                        let l10 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l11 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len12 = l11;
                        let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);

                        _rt::string_lift(bytes12)
                      };
                      Error::SendFailure(e27)
                    }
                    2 => {
                      let e27 = {
                        let l13 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l14 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len15 = l14;
                        let bytes15 = _rt::Vec::from_raw_parts(l13.cast(), len15, len15);

                        _rt::string_lift(bytes15)
                      };
                      Error::ReceiveFailure(e27)
                    }
                    3 => {
                      let e27 = {
                        let l16 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l17 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len18 = l17;
                        let bytes18 = _rt::Vec::from_raw_parts(l16.cast(), len18, len18);

                        _rt::string_lift(bytes18)
                      };
                      Error::ProtocolError(e27)
                    }
                    4 => {
                      let e27 = {
                        let l19 = i32::from(*ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<u8>());

                        match l19 {
                          0 => None,
                          1 => {
                            let e = {
                              let l20 = i32::from(*ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<u16>());
                              let l21 = *ptr3.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                              let l22 = *ptr3.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
                              let len23 = l22;
                              let bytes23 = _rt::Vec::from_raw_parts(l21.cast(), len23, len23);

                              CloseInfo{
                                code: l20 as u16,
                                reason: _rt::string_lift(bytes23),
                              }
                            };
                            Some(e)
                          }
                          _ => _rt::invalid_enum_discriminant(),
                        }
                      };
                      Error::Closed(e27)
                    }
                    n => {
                      debug_assert_eq!(n, 5, "invalid enum discriminant");
                      let e27 = {
                        let l24 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l25 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len26 = l25;
                        let bytes26 = _rt::Vec::from_raw_parts(l24.cast(), len26, len26);

                        _rt::string_lift(bytes26)
                      };
                      Error::Other(e27)
                    }
                  };

                  v27
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result28
          }
        }
      }
      impl WebsocketConnection {
        #[allow(unused_unsafe, clippy::all)]
        /// Returns a pollable that resolves when a message is available to read
        pub fn subscribe(&self,) -> Pollable{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "golem:websocket/client@1.5.0")]
            unsafe extern "C" {
              #[link_name = "[method]websocket-connection.subscribe"]
              fn wit_import0(_: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, ) -> i32{ unreachable!() }
            let ret = unsafe { wit_import0((self).handle() as i32) };
            unsafe { super::super::super::wasi::io::poll::Pollable::from_handle(ret as u32) }
          }
        }
      }

    }

  }
}
#[allow(dead_code, clippy::all)]
pub mod wasi {
  pub mod io {
    /// A poll API intended to let users wait for I/O events on multiple handles
    /// at once.
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod poll {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      /// `pollable` represents a single I/O event which may be ready, or not.

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct Pollable{
        handle: _rt::Resource<Pollable>,
      }

      impl Pollable{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for Pollable{
        #[inline]
        unsafe fn drop(_handle: u32) {
          #[cfg(not(target_arch = "wasm32"))]
          unreachable!();

          #[cfg(target_arch = "wasm32")]
          {
            #[link(wasm_import_module = "wasi:io/poll@0.2.3")]
            unsafe extern "C" {
              #[link_name = "[resource-drop]pollable"]
              fn drop(_: u32);
            }

            unsafe { drop(_handle) };
          }
        }
      }
      
      impl Pollable {
        #[allow(unused_unsafe, clippy::all)]
        /// Return the readiness of a pollable. This function never blocks.
        ///
        /// Returns `true` when the pollable is ready, and `false` otherwise.
        pub fn ready(&self,) -> bool{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/poll@0.2.3")]
            unsafe extern "C" {
              #[link_name = "[method]pollable.ready"]
              fn wit_import0(_: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, ) -> i32{ unreachable!() }
            let ret = unsafe { wit_import0((self).handle() as i32) };
            _rt::bool_lift(ret as u8)
          }
        }
      }
      impl Pollable {
        #[allow(unused_unsafe, clippy::all)]
        /// `block` returns immediately if the pollable is ready, and otherwise
        /// blocks until ready.
        ///
        /// This function is equivalent to calling `poll.poll` on a list
        /// containing only this pollable.
        pub fn block(&self,) -> (){
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/poll@0.2.3")]
            unsafe extern "C" {
              #[link_name = "[method]pollable.block"]
              fn wit_import0(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, ){ unreachable!() }
            unsafe { wit_import0((self).handle() as i32) };
          }
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      /// Poll for completion on a set of pollables.
      ///
      /// This function takes a list of pollables, which identify I/O sources of
      /// interest, and waits until one or more of the events is ready for I/O.
      ///
      /// The result `list<u32>` contains one or more indices of handles in the
      /// argument list that is ready for I/O.
      ///
      /// This function traps if either:
      /// - the list is empty, or:
      /// - the list contains more elements than can be indexed with a `u32` value.
      ///
      /// A timeout can be implemented by adding a pollable from the
      /// wasi-clocks API to the list.
      ///
      /// This function does not return a `result`; polling in itself does not
      /// do any I/O so it doesn't fail. If any of the I/O sources identified by
      /// the pollables has an error, it is indicated by marking the source as
      /// being ready for I/O.
      pub fn poll(in_: &[&Pollable],) -> _rt::Vec::<u32>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
          let vec0 = in_;
          let len0 = vec0.len();
          let layout0 = _rt::alloc::Layout::from_size_align_unchecked(vec0.len() * 4, 4);
          let result0 = if layout0.size() != 0 {
            let ptr = _rt::alloc::alloc(layout0).cast::<u8>();
            if ptr.is_null()
            {
              _rt::alloc::handle_alloc_error(layout0);
            }
            ptr
          }else {
            ::core::ptr::null_mut()
          };
          for (i, e) in vec0.into_iter().enumerate() {
            let base = result0.add(i * 4);
            {
              *base.add(0).cast::<i32>() = (e).handle() as i32;
            }
          }
          let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:io/poll@0.2.3")]
          unsafe extern "C" {
            #[link_name = "poll"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8, ){ unreachable!() }
          unsafe { wit_import2(result0, len0, ptr1) };
          let l3 = *ptr1.add(0).cast::<*mut u8>();
          let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let len5 = l4;
          let result6 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
          if layout0.size() != 0 {
            _rt::alloc::dealloc(result0.cast(), layout0);
          }
          result6
        }
      }

    }

  }
}
mod _rt {
  #![allow(dead_code, clippy::all)]


  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }
  pub unsafe fn bool_lift(val: u8) -> bool {
    if cfg!(debug_assertions) {
      match val {
        0 => false,
        1 => true,
        _ => panic!("invalid bool discriminant"),
      }
    } else {
      val != 0
    }
  }
  pub use alloc_crate::vec::Vec;
  pub use alloc_crate::alloc;
  pub use alloc_crate::string::String;
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      String::from_utf8_unchecked(bytes)
    }
  }
  pub unsafe fn invalid_enum_discriminant<T>() -> T {
    if cfg!(debug_assertions) {
      panic!("invalid enum discriminant")
    } else {
      unsafe { core::hint::unreachable_unchecked() }
    }
  }
  
  pub fn as_i64<T: AsI64>(t: T) -> i64 {
    t.as_i64()
  }

  pub trait AsI64 {
    fn as_i64(self) -> i64;
  }

  impl<'a, T: Copy + AsI64> AsI64 for &'a T {
    fn as_i64(self) -> i64 {
      (*self).as_i64()
    }
  }
  
  impl AsI64 for i64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  
  impl AsI64 for u64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  
  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  extern crate alloc as alloc_crate;
}

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.41.0:golem-websocket-rust:golem-websocket:golem-websocket:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1030] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x80\x07\x01A\x02\x01\
A\x05\x01B\x0a\x04\0\x08pollable\x03\x01\x01h\0\x01@\x01\x04self\x01\0\x7f\x04\0\
\x16[method]pollable.ready\x01\x02\x01@\x01\x04self\x01\x01\0\x04\0\x16[method]p\
ollable.block\x01\x03\x01p\x01\x01py\x01@\x01\x02in\x04\0\x05\x04\0\x04poll\x01\x06\
\x03\0\x12wasi:io/poll@0.2.3\x05\0\x02\x03\0\0\x08pollable\x01B$\x02\x03\x02\x01\
\x01\x04\0\x08pollable\x03\0\0\x01r\x02\x04code{\x06reasons\x04\0\x0aclose-info\x03\
\0\x02\x01k\x03\x01q\x06\x12connection-failure\x01s\0\x0csend-failure\x01s\0\x0f\
receive-failure\x01s\0\x0eprotocol-error\x01s\0\x06closed\x01\x04\0\x05other\x01\
s\0\x04\0\x05error\x03\0\x05\x01p}\x01q\x02\x04text\x01s\0\x06binary\x01\x07\0\x04\
\0\x07message\x03\0\x08\x04\0\x14websocket-connection\x03\x01\x01o\x02ss\x01p\x0b\
\x01k\x0c\x01i\x0a\x01j\x01\x0e\x01\x06\x01@\x02\x03urls\x07headers\x0d\0\x0f\x04\
\0$[static]websocket-connection.connect\x01\x10\x01h\x0a\x01j\0\x01\x06\x01@\x02\
\x04self\x11\x07message\x09\0\x12\x04\0![method]websocket-connection.send\x01\x13\
\x01j\x01\x09\x01\x06\x01@\x01\x04self\x11\0\x14\x04\0$[method]websocket-connect\
ion.receive\x01\x15\x01k\x09\x01j\x01\x16\x01\x06\x01@\x02\x04self\x11\x0atimeou\
t-msw\0\x17\x04\01[method]websocket-connection.receive-with-timeout\x01\x18\x01k\
{\x01ks\x01@\x03\x04self\x11\x04code\x19\x06reason\x1a\0\x12\x04\0\"[method]webs\
ocket-connection.close\x01\x1b\x01i\x01\x01@\x01\x04self\x11\0\x1c\x04\0&[method\
]websocket-connection.subscribe\x01\x1d\x03\0\x1cgolem:websocket/client@1.5.0\x05\
\x02\x04\04golem-websocket-rust:golem-websocket/golem-websocket\x04\0\x0b\x15\x01\
\0\x0fgolem-websocket\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-com\
ponent\x070.227.1\x10wit-bindgen-rust\x060.41.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen_rt::maybe_link_cabi_realloc();
}

