[package]
name = "golem-websocket"
version = "0.0.3"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Packages golem:websocket as a simple Rust crate"

[features]
default = ["p2"]
p2 = []
p3 = []

[dependencies]
wit-bindgen = { version = "0.58.0", default-features = false, features = ["async", "async-spawn", "macros", "inter-task-wakeup"] }

[package.metadata.component.target.dependencies]
"golem:websocket" = { path = "wit/deps/golem-websocket" }
