// ESM wrapper around the CJS common shim.
// Follows the same pattern as upstream Node.js test/common/index.mjs:
// re-exports all named bindings from the CJS shim for ESM test files.
//
// Note: We cannot use createRequire(import.meta.url) because import.meta.url
// is not populated in the QuickJS runtime. Instead we use the global require()
// with the known absolute path of the common shim in the test filesystem.

const common = require('/test/common/index.js');

const {
  isWindows,
  isAIX,
  isSunOS,
  isLinux,
  isDarwin,
  isFreeBSD,
  isOpenBSD,
  isMacOS,
  isMainThread,
  isDebug,
  hasCrypto,
  hasIntl,
  hasIPv6,
  hasMultiLocalhost,
  hasQuic,
  localhostIPv4,
  buildType,
  mustCall,
  mustCallAtLeast,
  mustNotCall,
  mustSucceed,
  mustNotMutateObjectDeep,
  skip,
  printSkipMessage,
  expectWarning,
  expectsError,
  platformTimeout,
  allowGlobals,
  enoughTestMem,
  invalidArgTypeHelper,
  skipIfEslintMissing,
  skipIfInspectorDisabled,
  skipIf32Bits,
  skipIfWorker,
  skipIfDumbTerminal,
  canCreateSymLink,
  runWithInvalidFD,
  spawnPromisified,
  escapePOSIXShell,
  pwdCommand,
  PIPE,
  parseTestFlags,
  isAlive,
  requireNoPackageJSONAbove,
  getArrayBufferViews,
  getBufferSources,
  isInsideDirWithUnusualChars,
  _checkMustCalls,
  _resetMustCalls,
} = common;

export {
  isWindows,
  isAIX,
  isSunOS,
  isLinux,
  isDarwin,
  isFreeBSD,
  isOpenBSD,
  isMacOS,
  isMainThread,
  isDebug,
  hasCrypto,
  hasIntl,
  hasIPv6,
  hasMultiLocalhost,
  hasQuic,
  localhostIPv4,
  buildType,
  mustCall,
  mustCallAtLeast,
  mustNotCall,
  mustSucceed,
  mustNotMutateObjectDeep,
  skip,
  printSkipMessage,
  expectWarning,
  expectsError,
  platformTimeout,
  allowGlobals,
  enoughTestMem,
  invalidArgTypeHelper,
  skipIfEslintMissing,
  skipIfInspectorDisabled,
  skipIf32Bits,
  skipIfWorker,
  skipIfDumbTerminal,
  canCreateSymLink,
  runWithInvalidFD,
  spawnPromisified,
  escapePOSIXShell,
  pwdCommand,
  PIPE,
  parseTestFlags,
  isAlive,
  requireNoPackageJSONAbove,
  getArrayBufferViews,
  getBufferSources,
  isInsideDirWithUnusualChars,
  _checkMustCalls,
  _resetMustCalls,
};

export default common;
