import http from 'node:http';

const PORT = 18080;
const VALID_API_KEY = 'test-brave-key';

const summaryAttempts = new Map();

const sendJson = (res, statusCode, body) => {
  res.writeHead(statusCode, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(body));
};

const ensureAuth = (req, res) => {
  if (req.headers['x-subscription-token'] !== VALID_API_KEY) {
    sendJson(res, 401, { message: 'Mock invalid subscription token' });
    return false;
  }

  return true;
};

const handleWebSearch = (req, res, url) => {
  if (!ensureAuth(req, res)) return;

  const query = url.searchParams.get('q') || '';

  if (query === 'trigger-rate-limit') {
    sendJson(res, 429, { message: 'Mock request limit reached' });
    return;
  }

  const summaryRequested = url.searchParams.get('summary') === 'true' || query.includes('summary');

  sendJson(res, 200, {
    query: { original: query },
    web: {
      results: [
        {
          title: `Web result for ${query}`,
          url: `https://example.com/web/${encodeURIComponent(query)}`,
          description: `Web description for ${query}`,
        },
      ],
    },
    optionsEcho: {
      count: url.searchParams.get('count'),
      text_decorations: url.searchParams.get('text_decorations'),
      spellcheck: url.searchParams.get('spellcheck'),
    },
    summarizer: summaryRequested ? { key: 'sum-key-1' } : undefined,
  });
};

const handleImageSearch = (req, res, url) => {
  if (!ensureAuth(req, res)) return;

  const query = url.searchParams.get('q') || '';
  sendJson(res, 200, {
    query: { original: query },
    results: [
      {
        title: `Image result for ${query}`,
        image_url: `https://example.com/images/${encodeURIComponent(query)}.jpg`,
      },
    ],
  });
};

const handleNewsSearch = (req, res, url) => {
  if (!ensureAuth(req, res)) return;

  const query = url.searchParams.get('q') || '';
  sendJson(res, 200, {
    query: { original: query },
    results: [
      {
        title: `News result for ${query}`,
        url: `https://example.com/news/${encodeURIComponent(query)}`,
      },
    ],
  });
};

const handleLocalPoiSearch = (req, res, url) => {
  if (!ensureAuth(req, res)) return;

  const ids = (url.searchParams.get('ids') || '').split(',').filter(Boolean);
  sendJson(res, 200, {
    results: ids.map((id) => ({
      id,
      name: `POI ${id}`,
      address: `${id} Example Street`,
    })),
  });
};

const handleLocalDescriptionsSearch = (req, res, url) => {
  if (!ensureAuth(req, res)) return;

  const ids = (url.searchParams.get('ids') || '').split(',').filter(Boolean);
  sendJson(res, 200, {
    descriptions: ids.map((id) => ({
      id,
      description: `Description for ${id}`,
    })),
  });
};

const handleSummarizerSearch = (req, res, url) => {
  if (!ensureAuth(req, res)) return;

  const key = url.searchParams.get('key') || '';
  const attempts = (summaryAttempts.get(key) || 0) + 1;
  summaryAttempts.set(key, attempts);

  if (attempts < 2) {
    sendJson(res, 200, { status: 'running' });
    return;
  }

  sendJson(res, 200, {
    status: 'complete',
    summary: [{ type: 'text', data: 'Mock summary generated by brave-search tests' }],
  });
};

const server = http.createServer((req, res) => {
  const method = req.method || 'GET';
  const url = new URL(req.url || '/', `http://localhost:${PORT}`);

  if (method === 'GET' && url.pathname === '/health') {
    sendJson(res, 200, { status: 'ok' });
    return;
  }

  if (method !== 'GET') {
    sendJson(res, 405, { message: 'Method Not Allowed' });
    return;
  }

  if (url.pathname === '/res/v1/web/search') {
    handleWebSearch(req, res, url);
    return;
  }

  if (url.pathname === '/res/v1/images/search') {
    handleImageSearch(req, res, url);
    return;
  }

  if (url.pathname === '/res/v1/news/search') {
    handleNewsSearch(req, res, url);
    return;
  }

  if (url.pathname === '/res/v1/local/pois') {
    handleLocalPoiSearch(req, res, url);
    return;
  }

  if (url.pathname === '/res/v1/local/descriptions') {
    handleLocalDescriptionsSearch(req, res, url);
    return;
  }

  if (url.pathname === '/res/v1/summarizer/search') {
    handleSummarizerSearch(req, res, url);
    return;
  }

  sendJson(res, 404, { message: `No route for ${method} ${url.pathname}` });
});

server.listen(PORT, () => {
  console.log(`Mock server listening on http://localhost:${PORT}`);
});
