package quickjs:fetch;

world fetch {
  export test1: func(port: u16);
  export test2: func(port: u16);
  export test3: func(port: u16);
  export test4: func(port: u16);
  export test4-buffered: func(port: u16);
  export test5: func(port: u16);
  export test6: func(port: u16);
  export test7: func();
  export test8: func(port: u16);
  export test9: func();
}
