package quickjs:fetch;

world fetch {
  export test1: func(port: u16);
  export test2: func(port: u16);
  export test3: func(port: u16);
  export test4: func(port: u16);
  export test4-buffered: func(port: u16);
  export test5: func(port: u16);
  export test6: func(port: u16);
  export test7: func();
  export test8: func(port: u16);
  export test9: func(port: u16);
  export test10: func(port: u16);
  export test11: func(port: u16);
  export test12: func(port: u16);
  export test13: func(port: u16);
  export test14: func(port: u16);
  export test15: func(port: u16);
  export test16: func(port: u16);
  export test17: func(port: u16);
  export test18: func(port: u16);
  export test19: func(port: u16);
  export test20: func(port: u16);
}
