package quickjs:fetch;

world fetch {
  export post-json-and-get: func(port: u16);
  export post-and-get-as-array-buffer: func(port: u16);
  export streaming-response-body: func(port: u16);
  export pipe-response-body-to-request: func(port: u16);
  export pipe-buffered-response-body-to-request: func(port: u16);
  export concurrent-post-and-get: func(port: u16);
  export post-with-slow-streaming-body: func(port: u16);
  export blob-operations: func();
  export post-with-blob-body: func(port: u16);
  export post-form-data-with-files: func(port: u16);
  export fetch-with-request-object: func(port: u16);
  export post-with-data-view-body: func(port: u16);
  export post-with-url-search-params: func(port: u16);
  export request-with-url-search-params: func(port: u16);
  export fetch-with-referrer: func(port: u16);
  export fetch-with-referrer-policy: func(port: u16);
  export fetch-with-credentials: func(port: u16);
  export redirect-follow: func(port: u16);
  export redirect-manual: func(port: u16);
  export redirect-error: func(port: u16);
  export redirect-loop: func(port: u16);
  export post-with-redirect: func(port: u16);
  export response-clone-basic: func(port: u16);
  export response-clone-streaming-body: func(port: u16);
  export response-clone-reuse-bodies: func(port: u16);
  export response-clone-headers: func(port: u16);
  export response-form-data: func(port: u16);
  }
