package quickjs:pollable;

world pollable {
  import wasi:clocks/monotonic-clock@0.2.3;
  import wasi:io/poll@0.2.3;

  export test: func() -> u64;
  export test-abortable-already-aborted: func();
  export test-abortable-not-aborted: func();
  export test-abortable-mid-wait: func();
  export test-abortable-race: func();
}
