package quickjs:abort-controller;

world abort-controller {
  export test-abort-basic: func();
  export test-abort-signal: func();
  export test-abort-timeout: func();
  export test-abort-event: func();
  export test-abort-reason: func();
  export test-abort-multiple-listeners: func();
}
