package quickjs:example3;

interface iface {
  resource hello {
    constructor(name: string);
    get-name: func() -> string;
    compare: static func(h1: borrow<hello>, h2: borrow<hello>) -> s32;
    merge: static func(h1: own<hello>, h2: own<hello>) -> hello;
  }
}

world example3 {
  export iface;
}
